### ISSUE TITLE
Epic:1 Story:1 Change navbar to always float at the top

### ISSUE THREAD

**Issue by TSeelig** [HaCSBCU/hacsbcu.github.io#112]
## Description
At current navbar goes down on the screen when 'home' is selected or when index.html is first loaded as can be seen below.

<img width="1440" alt="Site Index showing navbar position" src="https://user-images.githubusercontent.com/20642658/43153606-9d750384-8f69-11e8-9beb-676f65dbc8d9.png">

This is in general poor accessibility design and a nuisance when navigating.

## To Do
Redesign to have navbar always float at top of page at all times.

## Checklist

- [x] Navbar always floats at top of page.

**Comment by luketainton** [comment]
The template that I used has it like this - it'll be a pain to change it.

**Comment by TSeelig** [comment]
lemme take a crack at it, its set to float to the top anyway when you scroll bellow a certain point so we can just set that point to be essentially 0.
