### ISSUE TITLE
Cleanup repo

### ISSUE THREAD

**Issue by PandelisZ** [HaCSBCU/hacsbcu.github.io#15]
Remove all non-site related content from the repo. 

Ie: marketing / email to be moved to appropriate repos and all test/ideas to be branched out of master and any loose ends to be cleared and ignored such as sass files etc

**Comment by luketainton** [comment]
Has anyone started doing this? If not, I'll do some of it tonight if you want.

**Comment by luketainton** [comment]
@PandelisZ Are you still working on this?

**Comment by PandelisZ** [comment]
yeah, long term goal :P

**Comment by luketainton** [comment]
Do you need a hand w/ anything?

**Comment by PandelisZ** [comment]
Not atm after exams we can spec it out and do the things, also this is kind of relevant to the plan:

https://github.com/PandelisZ/spring-2017/blob/46f9511445dded6290025f941a8504cf0b569504/communities/hacs/community-impact-proposal.md#encouraging-more-building

check out that section on encouraging more building

**Comment by luketainton** [comment]
If the overhaul goes ahead, this issue will be made redundant.

**Comment by PandelisZ** [comment]
Psh i dont know who made this issue this repo is obviously perfect
