### ISSUE TITLE
.about-left image is broken cant fix

### ISSUE THREAD

**Issue by PandelisZ** [HaCSBCU/hacsbcu.github.io#20]
I spent half an hour trying to fix it, im now assigning it to you congrats @luketainton i think you might of broke it in a previous cleanup commit

**Comment by luketainton** [comment]
I've checked the last few commits, nothing should've broken that. Absolutely no idea.

**Comment by PandelisZ** [comment]
:/ dunno i tried some stuff to fix but i gave up cause it would be like a couple of pixels off

**Comment by luketainton** [comment]
Let Alex have a look

**Comment by alexwileyy** [comment]
Currently can't see the issue. Shall look later once I've finished work. Just work around it for the moment.

**Comment by luketainton** [comment]
![selection_002](https://cloud.githubusercontent.com/assets/22561713/23436742/968bfbd4-fe03-11e6-88b8-413a1676df4b.png)
