### ISSUE TITLE
Create new Committee section on index.html for the 2017 committee

### ISSUE THREAD

**Issue by luketainton** [HaCSBCU/hacsbcu.github.io#26]
Maybe a second committee section can be created and placed underneath the current one for the new committee?

**Comment by PandelisZ** [comment]
we can just replace them and create a page later with past commitees

**Comment by luketainton** [comment]
But at least for a few months the current committee will still be in charge

**Comment by luketainton** [comment]
I've created a new branch called Committee-2017 and put the updated source code in there. I've also (at least temporarily) disabled the animation on the 'Join Us Today' arrow which was causing the whole page to move if you were in between it and the next section.

**Comment by PandelisZ** [comment]
yeah that anim was super annoying

**Comment by luketainton** [comment]
I might've also sneaked in a little hyperlink to my HaCSHub test build ;)

**Comment by luketainton** [comment]
New additions are in the branch. Closing issue.
