### ISSUE TITLE
Create blog

### ISSUE THREAD

**Issue by luketainton** [HaCSBCU/hacsbcu.github.io#30]
As the 2016/17 committee has now been removed from the main site, we should create a new sub-page where these can be placed instead.

**Comment by PandelisZ** [comment]
Yeah this is gonna need a bunch of css work though as it should fit into our blogify milestone to bring blogging into the system. So we need pages, posts etc. Loads of css.

**Comment by luketainton** [comment]
CSS is ***not*** my strong point :(

**Comment by PandelisZ** [comment]
best time to learn!

**Comment by PandelisZ** [comment]
Possible inspiration: http://hmfaysal.me/Notepad/

**Comment by luketainton** [comment]
@PandelisZ Notepad may not be the best option, I'm gonna have a look around.

**Comment by luketainton** [comment]
The method that I've found requires a new repo, but it's completely feasible and easy to do.
