### ISSUE TITLE
Events need updating

### ISSUE THREAD

**Issue by luketainton** [HaCSBCU/hacsbcu.github.io#35]
I'm gonna change the Hackathon tile to Event, and make it GitHub Satellite. Have we got another workshop happening soon?

**Comment by PandelisZ** [comment]
:/ Exam jam? @CoffeeOwl97 do we?

**Comment by luketainton** [comment]
@PandelisZ @CoffeeOwl97 The build is currently failing, but don't be alarmed. I've removed the image and link for the old workshop and not replaced it, while waiting for a new Workshop idea.

If we're going for the exam jam, can an image be made? I believe that is @alexwileyy area of expertise?
