### ISSUE TITLE
Docker dev enviroment

### ISSUE THREAD

**Issue by PandelisZ** [HaCSBCU/hacsbcu.github.io#37]
Could do this to avoid all the gem setups.

Can build this into our curriculum and use it as a demo for a docker workshop

**Comment by luketainton** [comment]
Going to add in Vagrant and have Travis push the built website into gh-pages.

**Comment by luketainton** [comment]
@PandelisZ Can you check the files in 37-Vagrant? 

When a new PR comes in to merge to master, Travis runs its tests and commits the new site to gh-pages, minus the Vagrantfile etc., and pushes it.

**Comment by PandelisZ** [comment]
no. docker. also dont need it travis can do this natively all this are valid ideas but do within travis no vagrant needed

**Comment by luketainton** [comment]
Deleting branch 37.
