### ISSUE TITLE
Scaling of about/'who are we' section on mobile

### ISSUE THREAD

**Issue by TSeelig** [HaCSBCU/hacsbcu.github.io#48]
The about section only scales to fit the left half of the screen, leaving the right half as white space and causing the join button to be partially covered.

**Comment by PandelisZ** [comment]
Sites due for a reresh. LEts all hop on a call discus whats needed for freshers. This entire site was pretty much created, two days before and during freshers last year.

**Comment by TSeelig** [comment]
Posted is slack to get a call orgsnised within the next few days for this and a few other things (mainly freshers fair)
