### ISSUE TITLE
Create Sponsors section

### ISSUE THREAD

**Issue by TSeelig** [HaCSBCU/hacsbcu.github.io#54]
Make the sponsor footer look nicer.

**Comment by PandelisZ** [comment]
ok

**Comment by luketainton** [comment]
I'm gonna have a go at this. Creating branch 54-Footer.

**Comment by luketainton** [comment]
@PandelisZ @CoffeeOwl97 Can you pull 54-footer and test the site? I can't run Jekyll so don't know what the outcome of my changes is. Screenshots pls.

**Comment by luketainton** [comment]
We should create an entire section for sponsors, not just put them in the footer.

**Comment by luketainton** [comment]
I was making good progress, then realised I hadn't changed branch :(

**Comment by luketainton** [comment]
Creating branch 'Sponsors'.

**Comment by TSeelig** [comment]
Sponsor contract states that it should be as is in the footer, moving it into a dedicated sponsor section whould breach contract

**Comment by PandelisZ** [comment]
Thats a dumb technicallity, I'm sure they will fine with it being MORE promenant

**Comment by luketainton** [comment]
*DAMMIT TOM!* :D

But seriously, can we check with them?

**Comment by TSeelig** [comment]
Can we move the powered by .tech domains back into the footer so that were not in breech of the agreement? 
I don't want .Tech realising that we've changed how we plan to execute the agreement and causing trouble over it - we've already busy as it is and don't need more workload. + It could be a stain on potential relations with other sponsors/partners since we didn't ask them first.

**Comment by luketainton** [comment]
No we can’t. The footer is broken so if we put it there it breaks the layout. We need to speak with them in the short term while we figure out how to fix the issue, or redesign the site.

**Comment by TSeelig** [comment]
Put it back into the footer without breaking the site (the last load of commits were just me adjusting some CSS sizes) check out at https://hacs.tech/index1.html
Will put on index.html and delete index1.html later if no bugs are discovered.

**Comment by ChrisR1701** [comment]
For the time being, this looks good. At least we're not breaching an agreement. Can we merge this into the index file so it's live and then we can take a look at redesigning the footer when we look at the new site design? 😄

**Comment by ChrisR1701** [comment]
@luketainton @CoffeeOwl97 Can we close this issue as we're working on a new site design?
