### ISSUE TITLE
Update the site (see Epic 1)

### ISSUE THREAD

**Issue by alexwileyy** [HaCSBCU/hacsbcu.github.io#68]
# Site Design Proposal
If anybody is interested in this, I have some free design/development time coming up and I would like to devote it to the committee in some way or another; you guys have been doing real good. Constantly commits and stuff coming in which is great to see!

The Hacs website has been running for a while now and it looks great, however i've got some concepts for how to we could easily trump every society website out there. If the main dev team are interested, I can get a few concept designs over and you can flu with them and see where you take them?

This partly comes as I feel since making the website, the society has grown and matured, I feel as if this can be complemented with a new fresh face for the committee on the web where there is a higher emphasis on events and ease of access.

Let me know any thoughts down below, also happy to help out with development of said new design if we move ahead with it, however happy to take a back seat and provide feedback when needed if that's what you guys need/want.

That's all, happy HaCSing x

**Comment by luketainton** [comment]
We were considering re-designing the website, so you couldn't have stepped in at a better time! If you could send them over, that would be amazing.

**Comment by alexwileyy** [comment]
@luketainton it's my sixth sense at work Luke, can't beat it ;) 

Okay, well I will have to find some time to fit this in among other things, so what time of timeframe works for you? If I can aim to have a design submitted by the 10th November (There's quite a lot of buffer in there and the likelihood is that I can have it done next week).

Sound good?

**Comment by luketainton** [comment]
@alexwileyy Sounds brilliant. Don't worry though, we're not rushing - the site is fine, and all of this will be done in different branches.

**Comment by alexwileyy** [comment]
@luketainton okay buddy, no worries.

**Comment by ChrisR1701** [comment]
@alexwileyy I was talking with both @luketainton and @CoffeeOwl97 and we basically want to change the website so that it uses industry standard HTML, JS, CSS, etc. so that when we pass the society on, only a minimal amount is needed to be learnt to make changes. I also second Luke's comment to in the fact that you couldn't have said this at a better time 😄

**Comment by alexwileyy** [comment]
@ChrisR5 of course, and potentially you guys will need to consider the route that you want to take the build of this down. Unless I am needed I probably won't touch the build too much, other than laying out good foundations for styling and semantic HTML structure.

A decision does however need to be made whether we move to a front-end framework, or for simplicity stick with Jekyll. There are positives and negatives of both. This could be discussed in greater detail when transitioning the design into a product.

**Comment by PandelisZ** [comment]
Remember to just keep it easy guys. No matter what you do it will be changed in time. And that cycle will continue into infinity. Also. Don't get too dragged down by the site. There are much more important things that happen and the site is pretty much 0% of the society.

**Comment by luketainton** [comment]
@HaCSBCU/everyone To update all of you, I've found a really nice template by HTML5 UP, which I'd like to use to overhaul the site. Check out the gh-pages branch if you'd like to have a look, or go to https://test.luketainton.co.uk/hacs to see a live version.

Ideas and suggestions would be amazing, and contributions are even better!

**Comment by TSeelig** [comment]
Adjusted labels to cater for use of sprint/project board. Removed idea label as its now in development and created/added a 'Site 2.0' epic label. This will help to keep track of things in the project.

**Comment by luketainton** [comment]
Closing and replacing with a milestone.
